objects/CN_Competitor_Product_Price_to_Customer__c.object
<CustomObject>
    <fields>
        <fullName>CN_Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Competitor Product Price for Customer</relationshipLabel>
        <relationshipName>Competitor_Price_to_Customer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Competitor Product Price for Customer</label>
    <nameField>
        <displayFormat>CPN-{0000}</displayFormat>
        <label>Competitors Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitor Product Price for Customer</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CN_CPPC_Oppty__c.object
<CustomObject>
    <fields>
        <fullName>CN_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CPPC Opptys</relationshipLabel>
        <relationshipName>CPPC_Opptys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Competitor_Product_Price_for_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Competitor Product Price for Customer</label>
        <referenceTo>CN_Competitor_Product_Price_to_Customer__c</referenceTo>
        <relationshipLabel>CPPC Opptys</relationshipLabel>
        <relationshipName>CPPC_Opptys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CN_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>CPPC Opptys</relationshipLabel>
        <relationshipName>CPPC_Opptys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CPPC Oppty</label>
    <nameField>
        <displayFormat>L-{00000000}</displayFormat>
        <label>CPPC Oppty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPPC Opptys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CN_Oppty_Relation_Oppty_CPPC_Handler.cls
/*
 * ************************************************************************************************
 * Name : CN_Oppty_Relation_Oppty_CPPC_Handler
 * Description : 
 * Object :
 * Requirement :
 * Target :
 * Refer classes :
 * Author : Zhang ZhiHao
 * Create Date : 2024/2/23
 * Modify History :
 * ************************************************************************************************
 */
public without sharing class CN_Oppty_Relation_Oppty_CPPC_Handler implements Triggers.Handler{
    public void handle() {
		if(Trigger.isBefore && Trigger.isDelete) {
			beforeDeleteHandle();
		}
		if(Trigger.isAfter && Trigger.isInsert){
			afterInsertHandle();
		}
	}


    public void afterInsertHandle() {
        Set<Id> accountIds = new Set<Id>();
        List<Opportunity> opps = new List<Opportunity>();
        for(Opportunity opp: (List<Opportunity>)Trigger.new) {
            Id accountId = opp.AccountId;
            accountIds.add(accountId);
        }
    
 
        Map<Id, List<Id>> cppByAccountId = new Map<Id, List<Id>>();
        
        for (CN_Competitor_Product_Price_to_Customer__c cppc : [SELECT Id, CN_Account_Name__c FROM CN_Competitor_Product_Price_to_Customer__c WHERE CN_Account_Name__c IN :accountIds]) {
            if (!cppByAccountId.containsKey(cppc.CN_Account_Name__c)) {
                cppByAccountId.put(cppc.CN_Account_Name__c, new List<Id>());
            }
            cppByAccountId.get(cppc.CN_Account_Name__c).add(cppc.Id);
        }
    
    
        List<CN_CPPC_Oppty__c> recordsToInsert = new List<CN_CPPC_Oppty__c>();
        for (Opportunity opp : (List<Opportunity>) Trigger.new) {
            Id accountId = opp.AccountId;
            List<Id> cppIds = cppByAccountId.get(accountId);
                if(cppIds != null){
                    for (Id cppId : cppIds) {
                        CN_CPPC_Oppty__c record = new CN_CPPC_Oppty__c(
                                CN_Competitor_Product_Price_for_Customer__c = cppId,
                                CN_Opportunity__c = opp.id,
                                CN_Account__c = accountId
                            );
                        recordsToInsert.add(record);
                    }
                } 
            }
    
        if (!recordsToInsert.isEmpty()) {
            insert recordsToInsert;
        }
    }

    public void beforeDeleteHandle(){
        List<CN_CPPC_Oppty__c> recordsToDelete = new List<CN_CPPC_Oppty__c>();

        for (Opportunity deletedRecord : (List<Opportunity>)Trigger.old) {
            Id deletedCppId = deletedRecord.Id;
            List<CN_CPPC_Oppty__c> relatedRecords = [SELECT Id FROM CN_CPPC_Oppty__c WHERE CN_Opportunity__c = :deletedCppId];
    
            for (CN_CPPC_Oppty__c record : relatedRecords) {
                recordsToDelete.add(record);
            }
        }
        if (!recordsToDelete.isEmpty()) {
            delete recordsToDelete;
        }
    }
   
}